Find a valid toolchain instead of assuming a fixed name

diff --git a/crossbuild/environment b/crossbuild/environment
--- a/crossbuild/environment
+++ b/crossbuild/environment
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 PSDKR_PATH="${1}"
 
@@ -25,10 +25,21 @@ PSDKR_PATH=`realpath $PSDKR_PATH`
 # Find the source root of the project based on this script location
 SOURCE_ROOT=`realpath $(dirname $0)/..`
 
-HOST_TRIPLET="aarch64-none-linux-gnu"
-TOOLCHAIN="${PSDKR_PATH}/gcc-arm-9.2-2019.12-x86_64-${HOST_TRIPLET}/bin/${HOST_TRIPLET}-"
+# Definitions based on the PSDK root
 SYSROOT="${PSDKR_PATH}/targetfs/"
 PKG_CONFIG_LIBDIR="${SYSROOT}/usr/lib/pkgconfig:${SOURCE_ROOT}/pkgconfig"
+
+# Attempt to find a working cross compiler within the PSDKR
+HOST_TRIPLET="aarch64-none-linux-gnu"
+CROSS_CC=`find $PSDKR_PATH -name "${HOST_TRIPLET}-gcc" -exec sh -c "{} --version >/dev/null 2>&1" \;  -print`
+
+if test -z "$CROSS_CC"; then
+    echo "No toolchain found in \"$PSDKR_PATH\". Unable to locate ${HOST_TRIPLET}-gcc." >&2
+    exit 1
+fi
+
+# The toolchain prefix is the cross-compiler with the "gcc" stripped
+TOOLCHAIN=${CROSS_CC::-3}
 
 cat <<EOL
 [constants]
